### ISSUE TITLE
Problem with resize at Unity

### ISSUE THREAD

**Issue by DariaSereb** [magician-f/cocos-playable-demo#1]
Hi, I'm using your plugin for cocos and I have a problem with verification at the Unity. At their verification app there is problem with resize and orientation. When I open build in their verification  app, it doesn't adapte to size of the screen. Can you help me with this please?

**Comment by magician-f** [comment]
Horizontal and vertical screen adaptation needs to be done in the project, and "super html" is only responsible for packaging.
Many people are indeed troubled by horizontal and vertical screen adaptation. If there is time, I may provide a solution for horizontal and vertical screen adaptation. Please pay attention to the dynamics of this warehouse

**Comment by DariaSereb** [comment]
thank you for your answer, I resolve this problem by rebuilding project for web-mobile, I don't know why web mobile build made earlier wasn't working right. possibly some bug at Unity app. Sorry for interruption.
